name: rescreenapp
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

# dependencies:
# dev_dependencies:

flutter:
  uses-material-design: true
  generate: true
