name: rescreenapp
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

# dependencies:
# dev_dependencies:
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  integration_test:
    sdk: flutter
  mockito: 5.3.0

flutter:
  uses-material-design: true
  generate: true
